// Generated by CoffeeScript 1.6.3
var $comCloseButton, $comOpenButton, $sendButton, $startButton, recieveCallback, sentCallback, serial, serialConfig;

$comOpenButton = $('#com-open');

$comCloseButton = $('#com-close');

$startButton = $('#start');

$sendButton = $('#send');

$comOpenButton.click(function(event) {
  return serial.startConnection();
});

$comCloseButton.click(function(event) {
  return serial.endConnection();
});

$startButton.click(function(event) {
  return serial.startRecieve();
});

$sendButton.click(function(event) {
  var message;
  message = [0x01, 0x02, 0x03, 0x04, 0x05];
  return serial.sendData(message);
});

recieveCallback = function(data) {
  return console.log(data);
};

sentCallback = function(info) {
  return console.log(info);
};

serialConfig = {
  select: document.getElementById('ports'),
  bitrate: 9600,
  dataBits: "eight",
  parityBit: "no",
  stopBits: "one",
  recieveCallback: recieveCallback,
  sendCallback: sentCallback
};

serial = new Serial(serialConfig);
